### ISSUE TITLE
Trouble Installing

### ISSUE THREAD

**Issue by 4xlogan** [fionafibration/team-frotress-2#3]
![image](https://github.com/fionafibration/team-frotress-2/assets/155122358/333e45e9-472b-47da-8eda-005ba6ca7de9)

I'm completely new when it comes to installing stuff like this, so it seems like I may need a bit of a more thorough explanation :(. So far I've just tried copying "config_default.py" into config.cfg (I don't have a config.py file anywhere) and I've put a "console.log" file in my tf folder. I don't have any indication on Intiface that recognizes Team Fortress 2 is connected. Do I need to do anything with the other files?

**Comment by semper-lux** [comment]
Where did you unzip the project? Your `config_default.py` will be there: you can see it in the directory on the [home page of this repo](https://github.com/fionafibration/team-frotress-2).

Note that you will also have to install the included HUD if you would like compatibility with the medic. Simply place the `omphudsexy` folder in `.../Team Fortress 2/tf/custom`

**Comment by 4xlogan** [comment]
> Where did you unzip the project? Your `config_default.py` will be there: you can see it in the directory on the [home page of this repo](https://github.com/fionafibration/team-frotress-2).
> 
> Note that you will also have to install the included HUD if you would like compatibility with the medic. Simply place the `omphudsexy` folder in `.../Team Fortress 2/tf/custom`

I've tried putting the files in the Team Fortress 2 folder, the tf folder and the cfg folder. I already put omphud into custom and put '$classname' in each class config. I use an 'overrides' folder in cfg because I use mastercomfig if that means anything.

I'm just confused about where the files need to be unzipped to... I've already copied the contents of 'config_default.py' into 'config.cfg' in '.../Team Fortress 2/tf/cfg', so I'm assuming the other files need to be unzipped there as well?

This is what it looks like in '.../Team Fortress 2/tf/cfg':
![image](https://github.com/fionafibration/team-frotress-2/assets/155122358/fd10bb75-11f1-4506-8f6f-87e2d231d5dd)

**Comment by 4xlogan** [comment]
> > Where did you unzip the project? Your `config_default.py` will be there: you can see it in the directory on the [home page of this repo](https://github.com/fionafibration/team-frotress-2).
> > Note that you will also have to install the included HUD if you would like compatibility with the medic. Simply place the `omphudsexy` folder in `.../Team Fortress 2/tf/custom`
> 
> I've tried putting the files in the Team Fortress 2 folder, the tf folder and the cfg folder. I already put omphud into custom and put '$classname' in each class config. I use an 'overrides' folder in cfg because I use mastercomfig if that means anything.
> 
> I'm just confused about where the files need to be unzipped to... I've already copied the contents of 'config_default.py' into 'config.cfg' in '.../Team Fortress 2/tf/cfg', so I'm assuming the other files need to be unzipped there as well?
> 
> This is what it looks like in '.../Team Fortress 2/tf/cfg': ![image](https://private-user-images.githubusercontent.com/155122358/293406366-fd10bb75-11f1-4506-8f6f-87e2d231d5dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMzQ1MzYsIm5iZiI6MTcwNDEzNDIzNiwicGF0aCI6Ii8xNTUxMjIzNTgvMjkzNDA2MzY2LWZkMTBiYjc1LTExZjEtNDUwNi04ZjZmLTg3ZTJkMjMxZDVkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMVQxODM3MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMzI4MDY3N2VjNGQ0NjU1OWI3YWM2NGM3OGE4MGQ2ZjlkMjc1OGYwYjI3YTZkYzEzODUwNjBhYWViNGZiMzRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VUveI3bj8CJ5DDi5xi2ktX1RdcQFVYPGqFXCq3ruBKU)

Do I run one of these in cmd? I'm clueless ;-;

**Comment by fionafibration** [comment]
You do not copy the files into the Team Fortress 2 folder, I'd restore your config.cfg if you can. The config files are for the project itself and control the vibration functionality

For the config_default.py, see the readme:
 
> Copy config_default.py to config.py and fill out your game executable and console.log paths (console.log will be in tf folder)

Then you run main.py with python, which can be from command line or whichever other way you prefer.
