### ISSUE TITLE
Installation 

### ISSUE THREAD

**Issue by BlueSnow420** [fionafibration/team-frotress-2#4]
Hello there! I am completely clueless about how the installation works. Could there be something like a tutorial vid? Since the whole part with config.py is confusing me since I don't have it, sorry if I am a total moron, but that's how I am :3

**Comment by fionafibration** [comment]
There likely will not be a tutorial video from us at least. 

For the config, see the readme: 

> Setup

> Copy config_default.py to config.py and fill out your game executable and console.log paths (console.log will be in tf folder)

> If you want medic functionality, install OMPHUD-sexy on your game, make sure every class config has $classname in it somewhere, i.e. medic.cfg has a line $medic, heavyweapons.cfg has a line $heavyweapons.

> Note that usernames with non-ascii characters cannot be used at the moment.

Then you just run the python file `main.py`
