### ISSUE TITLE
File Not Found Error

### ISSUE THREAD

**Issue by 4xlogan** [fionafibration/team-frotress-2#5]
So I've installed all of the requirements listed in 'requirements.txt,' but now it says I am missing a certain file.
![error](https://github.com/fionafibration/team-frotress-2/assets/155122358/3eef33cf-839f-4172-890d-85e116dac60a)

**Comment by semper-lux** [comment]
It appears that you have not placed your TF2 executable path into `config.py`.

**Comment by 4xlogan** [comment]
> It appears that you have not placed your TF2 executable path into `config.py`.

That did the trick!

**Comment by semper-lux** [comment]
Great, enjoy the mod! Marking as closed.
